### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#204]
While a `1.0.0` release isn't exactly meaningful for a starter kit, it would be nice to finally have the kit stabilize. As such, here's what I'm thinking we need in order to meet this target:

* [x] Upgrade Babel from `^5.0.0` to `^6.0.0` (https://github.com/davezuko/react-redux-starter-kit/issues/150)
  * [x] Verify hot reloading works with react-transform
  * [x] Verify redbox-react / react-transform-catch-errors works (I'd be OK with dropping this if needed)
* [x] Implement css-modules https://github.com/davezuko/react-redux-starter-kit/issues/195
* [x] Add support for static assets
  * [x] Add favicon
* [x] Update all dependencies and devDependencies
  * [x] bump redux-simple-router to `^1.0.0`
* [x] Refactor sample app to follow ducks-like structure
* [x] Cleanup documentation
  * [x] Document express server
  * [x] Improve configuration section
  * [x] Verify all mentioned packages are accurate
  * [x] Document general deployment guidelines
* [x] Add cssnano plugin to postcss configuration
* [x] Replace autoprefixer with cssnano configuration
* [x] Replace all `console.log` with debug package (https://github.com/davezuko/react-redux-starter-kit/issues/218)

@neverfox suggested the css-modules addition, which would be awesome to add, and @justingreenberg has been keeping an eye on the Babel 6 transition so overall it looks fairly covered. Thanks for everyone's contributions, suggestions, and hard work, it's incredibly appreciated.

**Comment by mtsr** [comment]
I have css-modules working in combination with react-css-modules. I could make a PR as well, if desired.

**Comment by davezuko** [comment]
@mtsr that would be great, but would you be able to submit the PR's separately? I really want to take a look at the react-css-modules documentation before committing to it, so it might be helpful to get css-modules in and then possibly add react-css-modules afterward.

**Comment by mtsr** [comment]
Sure, easy enough. I use react-css-modules only for the improved syntax. It works without it, but mixing global and local classes becomes messy.

**Comment by neverfox** [comment]
I think sticking to a pure css-modules webpack configuration plus use of `classnames` is a good start. I have some issues with the was `react-css-modules` currently does things that may get worked out, but it's still baking.

**Comment by davezuko** [comment]
Would also be nice to add some documentation around FSA and the redux/modules pattern (suggested by @justingreenberg) a la https://github.com/erikras/react-redux-universal-hot-example#redux-modules-what-the-duck.

**Comment by neverfox** [comment]
Speaking of FSA, redux-actions is, from what I can tell, the de facto standard library when it comes to action creators and reducers. I'm familiar enough that I could easily work up a PR that switches out the bespoke actions and reducers for redux-actions versions, if you're open to it.

**Comment by davezuko** [comment]
Bumping:

* Fix hash changes when content is unchanged (https://github.com/davezuko/react-redux-starter-kit/issues/205)

To be a non-critical feature for the next release. I've been having a hell of a time getting this working, and don't want to hold off on another tag.

@neverfox I'm not 100% convinced on adding this dependency yet (purely for that reason, it's another dependency, albeit small). I mentioned to @justingreenberg that I'm really not a huge fan of the constant namespacing pattern encouraged by the "ducks" architecture, but other than that I'm guessing we can get it merged in.

**Comment by neverfox** [comment]
@davezuko I'm personally fond of a compromise on the action names: prefix with the reducer name, but not the app name (which seems unhelpful). I understand your hesitation on dependencies, but I think some of the de facto standards get used by people eventually anyway, and it can be somewhat cleaner and easier to wrap your head around than some homespun solutions like the current createReducer. In any case, it's there if you want to pull the trigger. Didn't take me any time.

**Comment by davezuko** [comment]
@neverfox I'd be ok using `redux-actions` if we could revert the constants the the vanilla-flux style (`COUNTER_INCREMENT`) constants (and export them as well). It still provides namespacing via the `COUNTER_` prefix, is arguably a better recognized pattern, and we can still leverage the standardization offered by `redux-actions` as you point out.

If you'd be willing to make those changes I'll merge this in. I appreciate the mention of redux-actions, I'd never heard of it before and it's definitely better than a solution local to the starter kit (which has the added benefit of reducing bloat).

**Comment by davezuko** [comment]
@neverfox just saw you updated it, so I replied just a minute too late :(. Would you be cool updating it to the use the `COUNTER_*`-style prefix?

**Comment by justingreenberg** [comment]
@davezuko you beat me, was about to write the same exact thing.

**Comment by neverfox** [comment]
I am cool with it.

**Comment by sarunast** [comment]
What about default 404 page ?

**Comment by davezuko** [comment]
@sarunast thought about that before, it might be a useful replacement for the sample About view.

**Comment by CurtisHumphrey** [comment]
What about adding something like rewire for mocking?

**Comment by davezuko** [comment]
@CurtisHumphrey while useful, it's a bit out of scope for the purposes this project.

**Comment by davezuko** [comment]
@justingreenberg for the time being I just threw in a simple copy script to move the assets from src/assets -> dist after compile. If you are able to get this working w/ the file loader I'd far prefer that, but this suffices for now.
