### ISSUE TITLE
2.0.0 Roadmap

### ISSUE THREAD

**Issue by davezuko** [davezuko/react-redux-starter-kit#386]
* [x] Replace Express with Koa
* [ ] Refactor configuration overrides
* [ ] Refactor webpack configuration
* [ ] Compile webpack manifest separately from vendor bundle
* [ ] Drop add-module-exports plugin
* [ ] Replace `cheap-module-eval-source-map` in development
  * needs investigation
* [ ] Re-implement better-npm-run
  * rationale: this will allow us to safely/always run tests w/ NODE_ENV=test, which opens up the door for improved configuration.
  *  Also, I'm considering dropping support for the application to be compiled with `NODE_ENV` development since it would simplify babel configuration.
* [ ] Enable automatic server restarts during local development (nodemon/piping/something else)
* [ ] Upgrade react-router to `^2.0.0`
* [x] Document compatible node engines in `package.json`
* [ ] Document recommended npm version (`^3.5.0`) in README
* [ ] Document example projects
* [ ] Document useful utilities (reselect, redux-state-history).
* [ ] Revisit https://github.com/davezuko/react-redux-starter-kit/issues/430
* [ ] Enzyme

More to come.

Also, do we cave and finally implement isomorphic rendering? I just fear the bloat.

**Comment by pkieltyka** [comment]
+1 for isomorphic rendering, the key is the find the conventions that keep thing simple. http://redux.js.org/docs/recipes/ServerRendering.html makes a lot of good simple suggestions. The redux examples/universal could be worth while looking at too.

As well, I'm pretty new to the react scene coming from writing Go for the last 2 years, prior worked on a large Angular app where we organized our app by "domain" instead of by "function". So I'm still a newb here, but I believe react apps could scale better if they were organized by domain instead of by function. I like the idea of "ducks" which I incorporated into this setup based off this kit: https://github.com/pkieltyka/rapp

**Comment by patrickheeney** [comment]
+1 for isomorphic rendering. I would also like to see this, but a "simpler" version then you often see in some other starter kits. I have not explored this in depth, but I am hoping it is just their implementation and not complex due to a massive amount of boilerplate. I also think being strict about the isomorphic rendering (simple implementation, more a how-to, starter version vs production quality) would help to reduce boilerplate.

Out of curiosity, why Koa vs Express for a dev server? Should the starter-kit use the most widely adopted tools to be a starter-kit into react development. Or is the starter-kit a production ready kit to start deploying real apps? It seems to me some of the choices will start to differ on 2.0 depending on the answer.

Some other things I have been toying with, just to inspire conversation for more 2.0 ideas:

- Revisit the tests? I have not explored testing react in depth yet, but the current setup feels like a lot of moving parts. Reading http://redux.js.org/docs/recipes/WritingTests.html and looking at a lot of popular react libraries (not starter-kits, so this could be off base) use mocha directly. I don't know that this covers as much capability, but it seemed better suited in my opinion for a starter kit then a complex robust solution for testing everything. If the starter-kit is bundling redux, then it would also be cool to test the redux implementation a little further.

- Webpack on the backend with hot reloading. I am not sure if this is stable but this has been explored by some people in the react community. It was paired with nodemon for automatic restarts and looked pretty incredible from the outside looking in.

- Consider other react usages. This is outside the scope of the starter-kit, but something I am hoping can be taken into account when naming and structuring things in this starter-kit. With react usage in electron apps and react-native apps, a lot of the app structure and config doesn't scale well for other use cases. For example, we have the `dir_client` (implying client code) pointing to `src` on the filesystem which acts as webpack root. Maybe things can be improved to take into account multiple use-cases, so the starter-kit can scale a little easier. Maybe `src` contains `client`. `server`, `shared`, and for others, `native > ios`, `native > android`, `electron`, etc. What about internal node modules, should they be in `src/lib`, `root/internal_modules`, etc. I am not trying to expand the scope, but rather present some scenarios that would make starting with this starter-kit harder to scale to other platforms.

**Comment by davezuko** [comment]
@patrickheeney :+1: awesome suggestions.

1) Testing, I definitely want to stick with Karma as I think it's most familiar and really doesn't require much configuration. I would really like to improve _how_ it's configured though, as it is messy currently.

2) Yes, but if we go with a `__tests__` in `~/src` how do you propose we do this? Different file extensions? I.e. `foo.spec.js` vs. something else?

3) Possibly, I only included some basic tests as an example, fully knowing they'd be ripped apart.

4) I really like this idea, but the only thing keeping me from doing it is the difficulty linting source code differently from tests given this structure, since they both would use the same `.eslintrc` file. We could probably have two separate lint tasks, but that kills the ability to integrate ESLint with the IDE. Maybe there's more that can be done here, as I do much prefer the `__tests__` pattern. :+1: 

5) Webpack on the BE looks nice, but I'd really like to limit the amount of code that requires webpack. This is part of the reason why I'd really like to get rid of the `ProvidePlugin`, at least by default.

6) Something to consider. I used `dir_client` with the intention of eventually making it easier to differentiate between client vs. server code, but the generic `~/src` directory goes against this. :+1: for reconsidering this structure.

7) :+1: on CSS as well.

8) I'm definitely thinking about consolidating webpack configuration back into a single file, but I do still like the idea of environment-specific overrides for the config file. If we can come up with a nice pluggable webpack system then that would be best.

9) Thanks for pointing that out, it sticks out to me every once in a while but I never do anything about it. 

### Additional Thoughts

We could get a _very simple_ isomorphic implementation integrated if we removed CSS modules and `root.resolve`. The server wouldn't have to do any pre-processing w/ webpack and would simply have to import the client app. This simplicity, however, would prevent people from easily extending the kit to utilize more advanced webpack functionality since we'd be avoiding the work required in favor of simplicity. Really, _really_ torn here, and it's about the point where I always say screw it and dismiss iso rendering for a boilerplate.

**Comment by pkieltyka** [comment]
re: additional thoughts -- I think the line should be drawn on whats necessary to write a full-featured app. Why are css modules in the way of server-side rendering?

btw, I wonder if https://github.com/istarkov/babel-plugin-webpack-loaders would help with server-side rendering of css modules.

**Comment by davezuko** [comment]
@pkieltyka they are in the way the same way that any webpack-specific functionality is (resolve.root is the other one that comes to mind). I'll look into the babel plugin, but the current hangup is that the React app source code cannot be imported without being first processed by webpack. For CSS modules, that's because the class names are dynamically generated by webpack.

I'd _really_ love to avoid going down the rabbit hole of using webpack on the server, but at this point it seems a necessary evil. In simpler apps, you could just pre-process the React app with babel for JSX and be done with it, but now we have to consider alternative solutions such as either that babel-plugin or webpackifying the server, the latter I at least find cumbersome.

**Comment by patrickheeney** [comment]
2, 4. What problem are we solving for this? Differentiating between browser and node tests? `CoreLayout.spec.js` for example could be the karma tests and `CoreLayout-test.js` could be the node tests run directly with mocha. I personally am going to keep mine separate as I don't need a browser to do most of the tests and karma is overkill for me. I will likely emulate rakt libraries for testing and then follow react-router for browser tests with karma. For linting I wonder if you can check for `__tests__` or `*spec.js` or `*test.js`. Will need to look into that more.

Isomorphic: I think if we can't keep it simple, clean, and flexible, then perhaps it is best to wait until v3 and some time for the tooling to catch up. There is also jspm and system.import and other things that may become the standard in the coming months. It may be more trouble then its worth to implement right now if it can't be done "right" enough for most people.

The one thing I would say is refactor the structure as if you were going to implement this now. Structure changes are time-consuming to keep in sync with the starterkit and I would rather do this once. This way everything is geared up to be used in multiple contexts later (native, isomorphic, client, server, etc),

**Comment by mikedevita** [comment]
:+1: for listing example projects, it will really help people who are new to both this kit and react/redux in general on how to tackle some of the more common tasks.. such as authentication based routing, and other things.

**Comment by rsilvestre** [comment]
Is it also possible to add *i18n* support

**Comment by patrickheeney** [comment]
Some more thoughts on existing topics:

Regarding tests: I am reverting my previous thoughts on some of this. I think karma is great at the starter-kit level. I needed to use mocha directly mainly because my app is half libraries at the moment. Ideally the tests could be ran directly through mocha and have the CI or locally run them through karma. (but mocha directly during dev). I'd still like to see them in `__tests__` as it has far more advantages in a real-world app. This might need some helper scripts but lots of open source examples on this.

Example projects: What will this provide that `awesome-react` or `awesome-redux` doesn't? I think you should likely just point to those instead. Unless you are building an `awesome-react-redux-starter-kit`, but what would it have that the others don't already?

Some new thoughts:

+1 for i18n. 

Lazy rendering and code splitting: https://github.com/rackt/example-react-router-server-rendering-lazy-routes .  I will be experimenting with this in the next few weeks.

Async lazy load reducers. I will also be experimenting with this in the coming weeks.

---

The last few suggestions come back to what is this starter-kit again. Is good simpler base for newcomers to the ecosystem. Or is it production ready that implements best practices at the expense of some learning.

**Comment by terakilobyte** [comment]
+1 for i18n.

I'm still pretty unversed in the React ecosystem and general webdev so I can't really add a lot to anything else.

Are you guys interested in shipping with a user authentication/authorization system? If so, I can write a PR for it once the server starts looking finalized.

**Comment by justingreenberg** [comment]
@davezuko @patrickheeney Ii have been away with the family and finding/moving into a new apartment, i didn't forget about you guys! i'm not sure if I'll get around to it today, but i need to run thru recent commits, read the issue threads and play some catch up before giving my 2 cents, but these are some things I've been thinking about (forgive me if these have already been implemented):

#### general ideas:
 - add RECIPES doc for common tasks, ie. removing semis, i18n, implementing `ProvidePlugin`
 - add TIPS or something like that to discuss optimizations like memoization, using selectors, etc
 - universal rendering - i'm not sure if the actual implementation is in the scope of this project, maybe better suited to a recipe section
 - simple JWT auth - now that we're using koa, i think having a super simple `auth` redux-module as a reference would be an awesome feature. we could just hard-code credentials and let users either implement their auth layer directly, proxy to existing strategy or hit a third party like auth0 or cognito

#### webpack/babel:
**Development**
 - [babel-plugin-typecheck](https://github.com/codemix/babel-plugin-typecheck): flow-style typechecking (optional, only used in development)

**Production**  
 - [babel-plugin-react-pure-components](https://github.com/thejameskyle/babel-plugin-react-pure-components) - converts pure component classes (stateless, `render()` only, no lifecycle methods) to simple function components, so components have backing instances during development (for HMR)
 - [babel-plugin-transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) - removes unused proptypes
 - [react-transform-sentry](https://github.com/luisrudge/react-transform-sentry) - this is a bit opinionated but would be a nice option (maybe belongs in recipes), sends component lifecycle to sentry via Raven

i have the webpack/babel stuff implemented so I can rebase and submit a PR if we all agree

#### v2 roadmap questions/comments:
 - Drop add-module-exports plugin - when i migrated us to babel 6, there were major interop issued with ES and CJS modules. i am pretty sure this plugin will be deprecated eventually when things stabilize a bit more. in the meantime we would just need to refactor some exports.
 - Replace cheap-module-eval-source-map in development - what's the rationale for this? 


-

so yeah i just wanted to say hi, throw out a few ideas, and let you guys know i'm still here :) 

also @davezuko nice article! [Where Flux Went Wrong](http://technologyadvice.github.io/where-flux-went-wrong) :+1:

**Comment by davezuko** [comment]
@justingreenberg happy new year to you as well, nice to hear from you! I've been slammed lately so will type out a better response when I get some time, but I would definitely be cool with using latest `react-router/redux-simple-router` as well as webpack. I'm still trying to understand the differences w/ webpack 2, so maybe if you could point me in the right direction, but I'd love to keep this kit as up-to-date as possible.

**Comment by nodegin** [comment]
need isomorphic too, love this kit very much, universal rendering is the missing part

**Comment by mikedevita** [comment]
@patrickheeney 
> Example projects: What will this provide that awesome-react or awesome-redux doesn't? I think you should likely just point to those instead. Unless you are building an awesome-react-redux-starter-kit, but what would it have that the others don't?

I think a list of example projects would help those who are new to this kit to learn how things are done with this kit.. I struggled for a few hours trying to get a navbar component to read in state from a layout. I eventually gave up and just included it in the views. a list of repo's or examples with basic things that *most* sites use (authentication, navigation, etc) would help tremendously.

**Comment by mjosh954** [comment]
Love this kit, however is there a way to persist the state for when the browser refreshes, like fetch it from LocalStorage? Or would that be better achieved if this boilerplate were isomorphic? If so then +1 to isomorphic :)

**Comment by mikedevita** [comment]
there is a middleware for that. just search for state localstorage

**Comment by asagage** [comment]
+1 for isomorphic - As a new user, I am having a very hard time jumping that hurdle with this otherwise awesome starter kit.

**Comment by thangngoc89** [comment]
A generator for generate boilerplate (like component, view, redux module, ..) would be nice

**Comment by davezuko** [comment]
@justingreenberg I like a lot of your suggestions, and have created a [gitter channel](https://gitter.im/davezuko/react-redux-starter-kit/react-redux-starter-kit-v2) so we can discuss things further. It's been crazy here so I still haven't had a chance to respond point-by-point, but I've read through it all and will be updating the milestone accordingly.

**Comment by davezuko** [comment]
## Discussion has been moved to https://gitter.im/davezuko/react-redux-starter-kit/react-redux-starter-kit-v2

**Comment by kodermax** [comment]
why did you replace koa to express?

**Comment by marshallford** [comment]
@kodermax [See this comment](https://github.com/davezuko/react-redux-starter-kit/pull/1000#issuecomment-246711234) @davezuko made on a merged PR.
